In [1]:
import pandas as pd
from pathlib import Path

# Project root path
BASE_DIR = Path.cwd()

# Folder where your Excel files are stored
RAW_DIR = BASE_DIR / "data" / "raw"

# File names
files = [
    "companies.xlsx",
    "balancesheet.xlsx",
    "profitandloss.xlsx",
    "cashflow.xlsx",
    "analysis.xlsx",
    "prosandcons.xlsx",
    "documents.xlsx"
]

# Dictionary to store DataFrames
dfs = {}

for file_name in files:
    file_path = RAW_DIR / file_name
    print(f"\n{'='*60}")
    print(f"Reading file: {file_name}")
    print(f"Path: {file_path}")

    df = pd.read_excel(file_path)
    dfs[file_name] = df

    print("Shape:", df.shape)
    print("Columns:")
    print(list(df.columns))
    display(df.head())

============================================================
Reading file: companies.xlsx
Path: f:\etl\data\raw\companies.xlsx
Shape: (93, 12)
Columns:
['Mkt Fintech — Nifty 100  |  Companies  |  92 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11']

,Mkt Fintech — Nifty 100 | Companies | 92 records,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
1,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10,1657,46,34.9
2,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,175,9,8.59
3,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1,363,11.6,13.64
4,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,67,96.5,14.7

============================================================
Reading file: balancesheet.xlsx
Path: f:\etl\data\raw\balancesheet.xlsx
Shape: (1313, 13)
Columns:
['Bluestock Fintech — Nifty 100  |  Balance Sheet  |  1,312 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']

,"Bluestock Fintech — Nifty 100 | Balance Sheet | 1,312 records",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,id,company_id,year,equity_capital,reserves,borrowings,other_liabilities,total_liabilities,fixed_assets,cwip,investments,other_asset,total_assets
1,136,ABB,Dec 2012,21,626,0,260,907,109,1,0,798,907
2,137,ABB,Mar 2014,21,767,0,351,1139,98,1,0,1040,1139
3,138,ABB,Mar 2015,21,916,0,436,1374,96,4,0,1274,1374
4,139,ABB,Mar 2016,21,1174,0,421,1616,108,3,0,1505,1616

============================================================
Reading file: profitandloss.xlsx
Path: f:\etl\data\raw\profitandloss.xlsx
Shape: (1277, 15)
Columns:
['Bluestock Fintech — Nifty 100  |  Profit & Loss  |  1,276 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']

,"Bluestock Fintech — Nifty 100 | Profit & Loss | 1,276 records",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
1,61,ABB,Dec 2012,1653,1451,202,12,33,0,19,215,33,145,68,25
2,62,ABB,Mar 2014,2276,2009,267,12,49,0,22,295,33,198,93,25
3,63,ABB,Mar 2015,2289,1977,312,14,48,0,15,344,34,229,108,29
4,64,ABB,Mar 2016,2614,2250,365,14,50,3,14,398,36,255,120,29

============================================================
Reading file: cashflow.xlsx
Path: f:\etl\data\raw\cashflow.xlsx
Shape: (1188, 7)
Columns:
['Bluestock Fintech — Nifty 100  |  Cash Flow  |  1,187 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6']

,"Bluestock Fintech — Nifty 100 | Cash Flow | 1,187 records",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,id,company_id,year,operating_activity,investing_activity,financing_activity,net_cash_flow
1,37,TCS,Mar-13,11615,-6038,-5729,-152
2,38,TCS,Mar-14,14751,-9452,-5673,-374
3,39,TCS,Mar-15,19369,-1807,-17168,394
4,40,TCS,Mar-16,19109,-5010,-9666,4433

============================================================
Reading file: analysis.xlsx
Path: f:\etl\data\raw\analysis.xlsx
Shape: (21, 6)
Columns:
['Bluestock Fintech — Nifty 100  |  Analysis  |  20 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5']

,Bluestock Fintech — Nifty 100 | Analysis | 20 records,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,id,company_id,compounded_sales_growth,compounded_profit_growth,stock_price_cagr,roe
1,1,HDFCBANK,10 Years: 21%,10 Years: 22%,10 Years: 15%,10 Years: 17%
2,10,SBILIFE,5 Years: 24%,5 Years: 6%,5 Years: 8%,5 Years 14%
3,11,SBILIFE,3 Years: 17%,3 Years: 9%,3 Years: 7%,3 Years: 13%
4,12,SBILIFE,TTM: 43%,TTM: 18%,1 Year: -2%,Last Year: 12%

============================================================
Reading file: prosandcons.xlsx
Path: f:\etl\data\raw\prosandcons.xlsx
Shape: (17, 4)
Columns:
['Bluestock Fintech — Nifty 100  |  Pros & Cons  |  16 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']

,Bluestock Fintech — Nifty 100 | Pros & Cons | 16 records,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,id,company_id,pros,cons
1,1,HDFCBANK,Company is expected to give good quarter,Stock is trading at 2.76 times its book value
2,2,HDFCBANK,Company has delivered good profit growth of 23...,Company has low interest coverage ratio.
3,3,HDFCBANK,Company has been maintaining a healthy dividen...,"Contingent liabilities of Rs.24,09,821 Cr."
4,4,HDFCBANK,Company's median sales growth is 16.4% of last...,"Earnings include an other income of Rs.1,55,87..."

============================================================
Reading file: documents.xlsx
Path: f:\etl\data\raw\documents.xlsx
Shape: (1586, 4)
Columns:
['Bluestock Fintech — Nifty 100  |  Documents  |  1,585 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']

,"Bluestock Fintech — Nifty 100 | Documents | 1,585 records",Unnamed: 1,Unnamed: 2,Unnamed: 3
0,id,company_id,Year,Annual_Report
1,1,ABB,2024,https://www.bseindia.com/xml-data/corpfiling/A...
2,2,ABB,2023,https://www.bseindia.com/xml-data/corpfiling/A...
3,3,ABB,2022,https://www.bseindia.com/bseplus/AnnualReport/...
4,4,ABB,2021,https://www.bseindia.com/bseplus/AnnualReport/...

In [9]:
companies_df = pd.read_excel(RAW_DIR / "companies.xlsx")
balancesheet_df = pd.read_excel(RAW_DIR / "balancesheet.xlsx")
profitandloss_df = pd.read_excel(RAW_DIR / "profitandloss.xlsx")
cashflow_df = pd.read_excel(RAW_DIR / "cashflow.xlsx")
analysis_df = pd.read_excel(RAW_DIR / "analysis.xlsx")
prosandcons_df = pd.read_excel(RAW_DIR / "prosandcons.xlsx")
documents_df = pd.read_excel(RAW_DIR / "documents.xlsx")

print("All files loaded successfully")

All files loaded successfully

In [8]:
list(companies_df.columns)

['Mkt Fintech — Nifty 100  |  Companies  |  92 records',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Unnamed: 9',
 'Unnamed: 10',
 'Unnamed: 11']

In [10]:
list(balancesheet_df.columns)

['Bluestock Fintech — Nifty 100  |  Balance Sheet  |  1,312 records',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Unnamed: 9',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12']

In [12]:
list(profitandloss_df.columns)

['Bluestock Fintech — Nifty 100  |  Profit & Loss  |  1,276 records',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Unnamed: 9',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13',
 'Unnamed: 14']

In [13]:
list(cashflow_df.columns)

['Bluestock Fintech — Nifty 100  |  Cash Flow  |  1,187 records',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6']

In [14]:
list(analysis_df.columns)

['Bluestock Fintech — Nifty 100  |  Analysis  |  20 records',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5']

In [15]:
list(prosandcons_df.columns)

['Bluestock Fintech — Nifty 100  |  Pros & Cons  |  16 records',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3']

In [16]:
list(documents_df.columns)

['Bluestock Fintech — Nifty 100  |  Documents  |  1,585 records',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3']

In [17]:
companies_df.head()

,Mkt Fintech — Nifty 100 | Companies | 92 records,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
1,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10,1657,46,34.9
2,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,175,9,8.59
3,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1,363,11.6,13.64
4,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,67,96.5,14.7

In [23]:
balancesheet_df.head()

,"Bluestock Fintech — Nifty 100 | Balance Sheet | 1,312 records",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,id,company_id,year,equity_capital,reserves,borrowings,other_liabilities,total_liabilities,fixed_assets,cwip,investments,other_asset,total_assets
1,136,ABB,Dec 2012,21,626,0,260,907,109,1,0,798,907
2,137,ABB,Mar 2014,21,767,0,351,1139,98,1,0,1040,1139
3,138,ABB,Mar 2015,21,916,0,436,1374,96,4,0,1274,1374
4,139,ABB,Mar 2016,21,1174,0,421,1616,108,3,0,1505,1616

In [22]:
profitandloss_df.head()

,"Bluestock Fintech — Nifty 100 | Profit & Loss | 1,276 records",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
1,61,ABB,Dec 2012,1653,1451,202,12,33,0,19,215,33,145,68,25
2,62,ABB,Mar 2014,2276,2009,267,12,49,0,22,295,33,198,93,25
3,63,ABB,Mar 2015,2289,1977,312,14,48,0,15,344,34,229,108,29
4,64,ABB,Mar 2016,2614,2250,365,14,50,3,14,398,36,255,120,29

In [21]:
cashflow_df.head()

,"Bluestock Fintech — Nifty 100 | Cash Flow | 1,187 records",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,id,company_id,year,operating_activity,investing_activity,financing_activity,net_cash_flow
1,37,TCS,Mar-13,11615,-6038,-5729,-152
2,38,TCS,Mar-14,14751,-9452,-5673,-374
3,39,TCS,Mar-15,19369,-1807,-17168,394
4,40,TCS,Mar-16,19109,-5010,-9666,4433

In [20]:
analysis_df.head()

,Bluestock Fintech — Nifty 100 | Analysis | 20 records,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,id,company_id,compounded_sales_growth,compounded_profit_growth,stock_price_cagr,roe
1,1,HDFCBANK,10 Years: 21%,10 Years: 22%,10 Years: 15%,10 Years: 17%
2,10,SBILIFE,5 Years: 24%,5 Years: 6%,5 Years: 8%,5 Years 14%
3,11,SBILIFE,3 Years: 17%,3 Years: 9%,3 Years: 7%,3 Years: 13%
4,12,SBILIFE,TTM: 43%,TTM: 18%,1 Year: -2%,Last Year: 12%

In [19]:
prosandcons_df.head()

,Bluestock Fintech — Nifty 100 | Pros & Cons | 16 records,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,id,company_id,pros,cons
1,1,HDFCBANK,Company is expected to give good quarter,Stock is trading at 2.76 times its book value
2,2,HDFCBANK,Company has delivered good profit growth of 23...,Company has low interest coverage ratio.
3,3,HDFCBANK,Company has been maintaining a healthy dividen...,"Contingent liabilities of Rs.24,09,821 Cr."
4,4,HDFCBANK,Company's median sales growth is 16.4% of last...,"Earnings include an other income of Rs.1,55,87..."

In [18]:
documents_df.head()

,"Bluestock Fintech — Nifty 100 | Documents | 1,585 records",Unnamed: 1,Unnamed: 2,Unnamed: 3
0,id,company_id,Year,Annual_Report
1,1,ABB,2024,https://www.bseindia.com/xml-data/corpfiling/A...
2,2,ABB,2023,https://www.bseindia.com/xml-data/corpfiling/A...
3,3,ABB,2022,https://www.bseindia.com/bseplus/AnnualReport/...
4,4,ABB,2021,https://www.bseindia.com/bseplus/AnnualReport/...

In [24]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path.cwd()
RAW_DIR = BASE_DIR / "data" / "raw"

companies_df     = pd.read_excel(RAW_DIR / "companies.xlsx",     header=1)
balancesheet_df  = pd.read_excel(RAW_DIR / "balancesheet.xlsx",  header=1)
profitandloss_df = pd.read_excel(RAW_DIR / "profitandloss.xlsx", header=1)
cashflow_df      = pd.read_excel(RAW_DIR / "cashflow.xlsx",      header=1)
analysis_df      = pd.read_excel(RAW_DIR / "analysis.xlsx",      header=1)
prosandcons_df   = pd.read_excel(RAW_DIR / "prosandcons.xlsx",   header=1)
documents_df     = pd.read_excel(RAW_DIR / "documents.xlsx",     header=1)

In [26]:
list(companies_df.columns)

['id',
 'company_logo',
 'company_name',
 'chart_link',
 'about_company',
 'website',
 'nse_profile',
 'bse_profile',
 'face_value',
 'book_value',
 'roce_percentage',
 'roe_percentage']

In [27]:
list(balancesheet_df.columns)

['id',
 'company_id',
 'year',
 'equity_capital',
 'reserves',
 'borrowings',
 'other_liabilities',
 'total_liabilities',
 'fixed_assets',
 'cwip',
 'investments',
 'other_asset',
 'total_assets']

In [28]:
list(profitandloss_df.columns)

['id',
 'company_id',
 'year',
 'sales',
 'expenses',
 'operating_profit',
 'opm_percentage',
 'other_income',
 'interest',
 'depreciation',
 'profit_before_tax',
 'tax_percentage',
 'net_profit',
 'eps',
 'dividend_payout']

In [29]:
list(cashflow_df.columns)

['id',
 'company_id',
 'year',
 'operating_activity',
 'investing_activity',
 'financing_activity',
 'net_cash_flow']

In [30]:
list(analysis_df.columns)

['id',
 'company_id',
 'compounded_sales_growth',
 'compounded_profit_growth',
 'stock_price_cagr',
 'roe']

In [31]:
list(prosandcons_df.columns)

['id', 'company_id', 'pros', 'cons']

In [32]:
list(documents_df.columns)

['id', 'company_id', 'Year', 'Annual_Report']

In [33]:
companies_clean = companies_df.copy()

# Standardise column names
companies_clean.columns = (
    companies_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

companies_clean.head()
list(companies_clean.columns)

['id',
 'company_logo',
 'company_name',
 'chart_link',
 'about_company',
 'website',
 'nse_profile',
 'bse_profile',
 'face_value',
 'book_value',
 'roce_percentage',
 'roe_percentage']

In [34]:
text_cols = [
    "company_name",
    "about_company",
    "website",
    "nse_profile",
    "bse_profile",
]

for col in text_cols:
    companies_clean[col] = companies_clean[col].astype(str).str.strip()

In [35]:
companies_clean.info()
companies_clean.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               92 non-null     object
 1   company_logo     91 non-null     object
 2   company_name     92 non-null     object
 3   chart_link       92 non-null     object
 4   about_company    92 non-null     object
 5   website          92 non-null     object
 6   nse_profile      92 non-null     object
 7   bse_profile      92 non-null     object
 8   face_value       91 non-null     float64
 9   book_value       91 non-null     float64
 10  roce_percentage  91 non-null     float64
 11  roe_percentage   90 non-null     float64
dtypes: float64(4), object(8)
memory usage: 8.8+ KB

,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
0,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10.0,1657.0,46.0,34.90
1,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10.0,175.0,9.0,8.59
2,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1.0,363.0,11.6,13.64
3,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10.0,67.0,96.5,14.70
4,ADANIPORTS,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Ports & Special Economic Zone Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Adani Ports & Special Economic Zone is in the ...,http://www.adaniports.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,2.0,265.0,12.9,18.10

In [37]:
balancesheet_clean = balancesheet_df.copy()

# Standardise column names
balancesheet_clean.columns = (
    balancesheet_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

balancesheet_clean.head()
list(balancesheet_clean.columns)

['id',
 'company_id',
 'year',
 'equity_capital',
 'reserves',
 'borrowings',
 'other_liabilities',
 'total_liabilities',
 'fixed_assets',
 'cwip',
 'investments',
 'other_asset',
 'total_assets']

In [39]:
balancesheet_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1312 entries, 0 to 1311
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1312 non-null   int64
 1   company_id         1312 non-null   object
 2   year               1312 non-null   object
 3   equity_capital     1312 non-null   float64
 4   reserves           1312 non-null   int64
 5   borrowings         1312 non-null   int64
 6   other_liabilities  1312 non-null   int64
 7   total_liabilities  1312 non-null   int64
 8   fixed_assets       1312 non-null   int64
 9   cwip               1312 non-null   int64
 10  investments        1312 non-null   int64
 11  other_asset        1312 non-null   int64
 12  total_assets       1312 non-null   int64
dtypes: float64(1), int64(10), object(2)
memory usage: 133.4+ KB

In [40]:
profitandloss_clean = profitandloss_df.copy()

In [41]:
profitandloss_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1276 entries, 0 to 1275
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1276 non-null   int64
 1   company_id         1276 non-null   object
 2   year               1276 non-null   object
 3   sales              1276 non-null   int64
 4   expenses           1276 non-null   int64
 5   operating_profit   1263 non-null   float64
 6   opm_percentage     1261 non-null   float64
 7   other_income       1276 non-null   int64
 8   interest           1276 non-null   int64
 9   depreciation       1276 non-null   int64
 10  profit_before_tax  1276 non-null   int64
 11  tax_percentage     1181 non-null   float64
 12  net_profit         1276 non-null   int64
 13  eps                1271 non-null   float64
 14  dividend_payout    1173 non-null   float64
dtypes: float64(5), int64(8), object(2)
memory usage: 149.7+ KB

In [42]:
cashflow_clean = cashflow_df.copy()

In [43]:
analysis_clean = analysis_df.copy()

In [44]:
prosandcons_clean = prosandcons_df.copy()

In [45]:
documents_clean = documents_df.copy()

In [46]:
cashflow_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1187 entries, 0 to 1186
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  1187 non-null   int64
 1   company_id          1187 non-null   object
 2   year                1187 non-null   object
 3   operating_activity  1185 non-null   float64
 4   investing_activity  1185 non-null   float64
 5   financing_activity  1185 non-null   float64
 6   net_cash_flow       1185 non-null   float64
dtypes: float64(4), int64(1), object(2)
memory usage: 65.0+ KB

In [47]:
analysis_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        20 non-null     int64
 1   company_id                20 non-null     object
 2   compounded_sales_growth   20 non-null     object
 3   compounded_profit_growth  20 non-null     object
 4   stock_price_cagr          20 non-null     object
 5   roe                       20 non-null     object
dtypes: int64(1), object(5)
memory usage: 1.1+ KB

In [48]:
prosandcons_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          16 non-null     int64
 1   company_id  16 non-null     object
 2   pros        11 non-null     object
 3   cons        15 non-null     object
dtypes: int64(1), object(3)
memory usage: 644.0+ bytes

In [49]:
documents_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1585 entries, 0 to 1584
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1585 non-null   int64
 1   company_id     1585 non-null   object
 2   Year           1585 non-null   int64
 3   Annual_Report  1533 non-null   object
dtypes: int64(2), object(2)
memory usage: 49.7+ KB

In [50]:
dim_company = companies_clean[[
    "id",
    "company_name",
    "about_company",
    "website",
    "nse_profile",
    "bse_profile",
    "face_value",
    "book_value",
    "roce_percentage",
    "roe_percentage",
]].copy()

# Rename "id" to "company_id" for consistency
dim_company = dim_company.rename(columns={"id": "company_id"})

# Ensure company_id is string and stripped
dim_company["company_id"] = dim_company["company_id"].astype(str).str.strip()

dim_company.head()
dim_company.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   company_id       92 non-null     object
 1   company_name     92 non-null     object
 2   about_company    92 non-null     object
 3   website          92 non-null     object
 4   nse_profile      92 non-null     object
 5   bse_profile      92 non-null     object
 6   face_value       91 non-null     float64
 7   book_value       91 non-null     float64
 8   roce_percentage  91 non-null     float64
 9   roe_percentage   90 non-null     float64
dtypes: float64(4), object(6)
memory usage: 7.3+ KB

In [51]:
balancesheet_clean = balancesheet_df.copy()

balancesheet_clean.columns = (
    balancesheet_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

balancesheet_clean["company_id"] = balancesheet_clean["company_id"].astype(str).str.strip()
balancesheet_clean["year"] = balancesheet_clean["year"].astype(str).str.strip()

balancesheet_clean.head()
balancesheet_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1312 entries, 0 to 1311
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1312 non-null   int64
 1   company_id         1312 non-null   object
 2   year               1312 non-null   object
 3   equity_capital     1312 non-null   float64
 4   reserves           1312 non-null   int64
 5   borrowings         1312 non-null   int64
 6   other_liabilities  1312 non-null   int64
 7   total_liabilities  1312 non-null   int64
 8   fixed_assets       1312 non-null   int64
 9   cwip               1312 non-null   int64
 10  investments        1312 non-null   int64
 11  other_asset        1312 non-null   int64
 12  total_assets       1312 non-null   int64
dtypes: float64(1), int64(10), object(2)
memory usage: 133.4+ KB

In [52]:
balancesheet_clean.head().to_string()

'    id company_id      year  equity_capital  reserves  borrowings  other_liabilities  total_liabilities  fixed_assets  cwip  investments  other_asset  total_assets\n0  136        ABB  Dec 2012            21.0       626           0                260                907           109     1            0          798           907\n1  137        ABB  Mar 2014            21.0       767           0                351               1139            98     1            0         1040          1139\n2  138        ABB  Mar 2015            21.0       916           0                436               1374            96     4            0         1274          1374\n3  139        ABB  Mar 2016            21.0      1174           0                421               1616           108     3            0         1505          1616\n4  140        ABB  Mar 2017            21.0      1366           0                679               2066           110     6            0         1950          2066'

In [53]:
import re

balancesheet_clean = balancesheet_clean.copy()

# Extract year as 4-digit number
balancesheet_clean["fiscal_year"] = (
    balancesheet_clean["year"]
    .str.extract(r"(\d{4})", expand=False)  # gets '2012', '2014', etc.
    .astype(int)
)

In [54]:
balancesheet_clean[["year", "fiscal_year"]].head(10)

       year  fiscal_year
0  Dec 2012         2012
1  Mar 2014         2014
2  Mar 2015         2015
3  Mar 2016         2016
4  Mar 2017         2017
5  Mar 2018         2018
6  Mar 2019         2019
7  Mar 2020         2020
8  Mar 2021         2021
9  Mar 2022         2022

In [55]:
fact_balance_sheet = balancesheet_clean[[
    "company_id",
    "fiscal_year",
    "equity_capital",
    "reserves",
    "borrowings",
    "other_liabilities",
    "total_liabilities",
    "fixed_assets",
    "cwip",
    "investments",
    "other_asset",
    "total_assets",
]].copy()

# Optional: compute a few ratios
fact_balance_sheet["debt_to_equity"] = (
    fact_balance_sheet["borrowings"] / fact_balance_sheet["equity_capital"]
)

fact_balance_sheet["equity_ratio"] = (
    (fact_balance_sheet["equity_capital"] + fact_balance_sheet["reserves"])
    / fact_balance_sheet["total_assets"]
)

fact_balance_sheet.head()
fact_balance_sheet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1312 entries, 0 to 1311
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   company_id         1312 non-null   object
 1   fiscal_year        1312 non-null   int64
 2   equity_capital     1312 non-null   float64
 3   reserves           1312 non-null   int64
 4   borrowings         1312 non-null   int64
 5   other_liabilities  1312 non-null   int64
 6   total_liabilities  1312 non-null   int64
 7   fixed_assets       1312 non-null   int64
 8   cwip               1312 non-null   int64
 9   investments        1312 non-null   int64
 10  other_asset        1312 non-null   int64
 11  total_assets       1312 non-null   int64
 12  debt_to_equity     1312 non-null   float64
 13  equity_ratio       1312 non-null   float64
dtypes: float64(3), int64(10), object(1)
memory usage: 143.6+ KB

In [56]:
fact_balance_sheet.head()
fact_balance_sheet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1312 entries, 0 to 1311
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   company_id         1312 non-null   object
 1   fiscal_year        1312 non-null   int64
 2   equity_capital     1312 non-null   float64
 3   reserves           1312 non-null   int64
 4   borrowings         1312 non-null   int64
 5   other_liabilities  1312 non-null   int64
 6   total_liabilities  1312 non-null   int64
 7   fixed_assets       1312 non-null   int64
 8   cwip               1312 non-null   int64
 9   investments        1312 non-null   int64
 10  other_asset        1312 non-null   int64
 11  total_assets       1312 non-null   int64
 12  debt_to_equity     1312 non-null   float64
 13  equity_ratio       1312 non-null   float64
dtypes: float64(3), int64(10), object(1)
memory usage: 143.6+ KB

In [57]:
profitandloss_clean = profitandloss_df.copy()

profitandloss_clean.columns = (
    profitandloss_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

profitandloss_clean["company_id"] = profitandloss_clean["company_id"].astype(str).str.strip()
profitandloss_clean["year"] = profitandloss_clean["year"].astype(str).str.strip()

profitandloss_clean.head()
profitandloss_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1276 entries, 0 to 1275
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1276 non-null   int64
 1   company_id         1276 non-null   object
 2   year               1276 non-null   object
 3   sales              1276 non-null   int64
 4   expenses           1276 non-null   int64
 5   operating_profit   1263 non-null   float64
 6   opm_percentage     1261 non-null   float64
 7   other_income       1276 non-null   int64
 8   interest           1276 non-null   int64
 9   depreciation       1276 non-null   int64
 10  profit_before_tax  1276 non-null   int64
 11  tax_percentage     1181 non-null   float64
 12  net_profit         1276 non-null   int64
 13  eps                1271 non-null   float64
 14  dividend_payout    1173 non-null   float64
dtypes: float64(5), int64(8), object(2)
memory usage: 149.7+ KB

In [59]:
import re

profitandloss_clean["fiscal_year"] = (
    profitandloss_clean["year"]
    .str.extract(r"(\d{4})", expand=False)
)

# Option 1: keep as float with NaN (simplest)
profitandloss_clean["fiscal_year"] = profitandloss_clean["fiscal_year"].astype("float")

# If you want int but allow NaN, you can use Int64 (nullable int)
# profitandloss_clean["fiscal_year"] = profitandloss_clean["fiscal_year"].astype("Int64")

profitandloss_clean[["year", "fiscal_year"]].head(20)

        year  fiscal_year
0   Dec 2012       2012.0
1   Mar 2014       2014.0
2   Mar 2015       2015.0
3   Mar 2016       2016.0
4   Mar 2017       2017.0
5   Mar 2018       2018.0
6   Mar 2019       2019.0
7   Mar 2020       2020.0
8   Mar 2021       2021.0
9   Mar 2022       2022.0
10  Mar 2023       2023.0
11  Mar 2024       2024.0
12       TTM          NaN
13  Mar 2014       2014.0
14  Mar 2015       2015.0
15  Mar 2016       2016.0
16  Mar 2017       2017.0
17  Mar 2018       2018.0
18  Mar 2019       2019.0
19  Mar 2020       2020.0

In [60]:
profitandloss_clean[["year", "fiscal_year"]].head(20)
profitandloss_clean["fiscal_year"].isna().sum()

np.int64(100)

In [61]:
profitandloss_clean[["year", "fiscal_year"]].head(10)

       year  fiscal_year
0  Dec 2012       2012.0
1  Mar 2014       2014.0
2  Mar 2015       2015.0
3  Mar 2016       2016.0
4  Mar 2017       2017.0
5  Mar 2018       2018.0
6  Mar 2019       2019.0
7  Mar 2020       2020.0
8  Mar 2021       2021.0
9  Mar 2022       2022.0

In [2]:
import pandas as pd
from pathlib import Path
import re

# Adjust path if needed
RAW_DIR = Path("data/raw")

# 1) Read the original Excel
profitandloss_df = pd.read_excel(RAW_DIR / "profitandloss.xlsx", header=1)

# 2) Clean columns and base fields
profitandloss_clean = profitandloss_df.copy()

profitandloss_clean.columns = (
    profitandloss_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

profitandloss_clean["company_id"] = profitandloss_clean["company_id"].astype(str).str.strip()
profitandloss_clean["year"] = profitandloss_clean["year"].astype(str).str.strip()

# 3) Extract fiscal_year allowing NaN
profitandloss_clean["fiscal_year"] = (
    profitandloss_clean["year"]
    .str.extract(r"(\d{4})", expand=False)
)

profitandloss_clean["fiscal_year"] = profitandloss_clean["fiscal_year"].astype("float")  # or "Int64"

profitandloss_clean.head()
profitandloss_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1276 entries, 0 to 1275
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1276 non-null   int64
 1   company_id         1276 non-null   object
 2   year               1276 non-null   object
 3   sales              1276 non-null   int64
 4   expenses           1276 non-null   int64
 5   operating_profit   1263 non-null   float64
 6   opm_percentage     1261 non-null   float64
 7   other_income       1276 non-null   int64
 8   interest           1276 non-null   int64
 9   depreciation       1276 non-null   int64
 10  profit_before_tax  1276 non-null   int64
 11  tax_percentage     1181 non-null   float64
 12  net_profit         1276 non-null   int64
 13  eps                1271 non-null   float64
 14  dividend_payout    1173 non-null   float64
 15  fiscal_year        1176 non-null   float64
dtypes: float64(6), int64(8), object(2)
memory usage: 159.6+ KB

In [3]:
fact_profit_loss = profitandloss_clean[[
    "company_id",
    "fiscal_year",
    "sales",
    "expenses",
    "operating_profit",
    "opm_percentage",
    "other_income",
    "interest",
    "depreciation",
    "profit_before_tax",
    "tax_percentage",
    "net_profit",
    "eps",
    "dividend_payout",
]].copy()

# Extra ratios (optional)
fact_profit_loss["net_margin"] = (
    fact_profit_loss["net_profit"] / fact_profit_loss["sales"]
)

fact_profit_loss["operating_margin"] = (
    fact_profit_loss["operating_profit"] / fact_profit_loss["sales"]
)

fact_profit_loss.head()
fact_profit_loss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1276 entries, 0 to 1275
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   company_id         1276 non-null   object
 1   fiscal_year        1176 non-null   float64
 2   sales              1276 non-null   int64
 3   expenses           1276 non-null   int64
 4   operating_profit   1263 non-null   float64
 5   opm_percentage     1261 non-null   float64
 6   other_income       1276 non-null   int64
 7   interest           1276 non-null   int64
 8   depreciation       1276 non-null   int64
 9   profit_before_tax  1276 non-null   int64
 10  tax_percentage     1181 non-null   float64
 11  net_profit         1276 non-null   int64
 12  eps                1271 non-null   float64
 13  dividend_payout    1173 non-null   float64
 14  net_margin         1275 non-null   float64
 15  operating_margin   1262 non-null   float64
dtypes: float64(8), int64(7), object(1)
memory usage: 159.6+ KB

In [5]:
from pathlib import Path
import pandas as pd
import re

RAW_DIR = Path("data/raw")

# 1) Read Excel
cashflow_df = pd.read_excel(RAW_DIR / "cashflow.xlsx", header=1)

# 2) Clean columns
cashflow_clean = cashflow_df.copy()

cashflow_clean.columns = (
    cashflow_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

cashflow_clean["company_id"] = cashflow_clean["company_id"].astype(str).str.strip()
cashflow_clean["year"] = cashflow_clean["year"].astype(str).str.strip()

# 3) Extract fiscal_year
cashflow_clean["fiscal_year"] = (
    cashflow_clean["year"]
    .str.extract(r"(\d{4})", expand=False)
)

cashflow_clean["fiscal_year"] = cashflow_clean["fiscal_year"].astype("float")  # or "Int64"

cashflow_clean.head()
cashflow_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1187 entries, 0 to 1186
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  1187 non-null   int64
 1   company_id          1187 non-null   object
 2   year                1187 non-null   object
 3   operating_activity  1185 non-null   float64
 4   investing_activity  1185 non-null   float64
 5   financing_activity  1185 non-null   float64
 6   net_cash_flow       1185 non-null   float64
 7   fiscal_year         1175 non-null   float64
dtypes: float64(5), int64(1), object(2)
memory usage: 74.3+ KB

In [6]:
fact_cash_flow = cashflow_clean[[
    "company_id",
    "fiscal_year",
    "operating_activity",
    "investing_activity",
    "financing_activity",
    "net_cash_flow",
]].copy()

fact_cash_flow["free_cash_flow"] = (
    fact_cash_flow["operating_activity"] - fact_cash_flow["investing_activity"]
)

fact_cash_flow.head()
fact_cash_flow.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1187 entries, 0 to 1186
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   company_id          1187 non-null   object
 1   fiscal_year         1175 non-null   float64
 2   operating_activity  1185 non-null   float64
 3   investing_activity  1185 non-null   float64
 4   financing_activity  1185 non-null   float64
 5   net_cash_flow       1185 non-null   float64
 6   free_cash_flow      1185 non-null   float64
dtypes: float64(6), object(1)
memory usage: 65.0+ KB

In [7]:
fact_cash_flow.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1187 entries, 0 to 1186
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   company_id          1187 non-null   object
 1   fiscal_year         1175 non-null   float64
 2   operating_activity  1185 non-null   float64
 3   investing_activity  1185 non-null   float64
 4   financing_activity  1185 non-null   float64
 5   net_cash_flow       1185 non-null   float64
 6   free_cash_flow      1185 non-null   float64
dtypes: float64(6), object(1)
memory usage: 65.0+ KB

In [9]:
import pandas as pd
from pathlib import Path

RAW_DIR = Path("data/raw")

analysis_df = pd.read_excel(RAW_DIR / "analysis.xlsx", header=1)
analysis_df.head()
analysis_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        20 non-null     int64
 1   company_id                20 non-null     object
 2   compounded_sales_growth   20 non-null     object
 3   compounded_profit_growth  20 non-null     object
 4   stock_price_cagr          20 non-null     object
 5   roe                       20 non-null     object
dtypes: int64(1), object(5)
memory usage: 1.1+ KB

In [10]:
analysis_clean = analysis_df.copy()

analysis_clean.columns = (
    analysis_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

analysis_clean["company_id"] = analysis_clean["company_id"].astype(str).str.strip()

fact_analysis = analysis_clean.copy()

fact_analysis.head()
fact_analysis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        20 non-null     int64
 1   company_id                20 non-null     object
 2   compounded_sales_growth   20 non-null     object
 3   compounded_profit_growth  20 non-null     object
 4   stock_price_cagr          20 non-null     object
 5   roe                       20 non-null     object
dtypes: int64(1), object(5)
memory usage: 1.1+ KB

In [11]:
prosandcons_df = pd.read_excel(RAW_DIR / "prosandcons.xlsx", header=1)

prosandcons_clean = prosandcons_df.copy()

prosandcons_clean.columns = (
    prosandcons_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

prosandcons_clean["company_id"] = prosandcons_clean["company_id"].astype(str).str.strip()

fact_pros_cons = prosandcons_clean.copy()

fact_pros_cons.head()
fact_pros_cons.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          16 non-null     int64
 1   company_id  16 non-null     object
 2   pros        11 non-null     object
 3   cons        15 non-null     object
dtypes: int64(1), object(3)
memory usage: 644.0+ bytes

In [12]:
documents_df = pd.read_excel(RAW_DIR / "documents.xlsx", header=1)

documents_clean = documents_df.copy()

documents_clean.columns = (
    documents_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

documents_clean["company_id"] = documents_clean["company_id"].astype(str).str.strip()

documents_clean.head()
documents_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1585 entries, 0 to 1584
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1585 non-null   int64
 1   company_id     1585 non-null   object
 2   year           1585 non-null   int64
 3   annual_report  1533 non-null   object
dtypes: int64(2), object(2)
memory usage: 49.7+ KB

In [14]:
import pandas as pd
from pathlib import Path
import re

RAW_DIR = Path("data/raw")

companies_df     = pd.read_excel(RAW_DIR / "companies.xlsx",     header=1)
balancesheet_df  = pd.read_excel(RAW_DIR / "balancesheet.xlsx",  header=1)
profitandloss_df = pd.read_excel(RAW_DIR / "profitandloss.xlsx", header=1)
cashflow_df      = pd.read_excel(RAW_DIR / "cashflow.xlsx",      header=1)
analysis_df      = pd.read_excel(RAW_DIR / "analysis.xlsx",      header=1)
prosandcons_df   = pd.read_excel(RAW_DIR / "prosandcons.xlsx",   header=1)
documents_df     = pd.read_excel(RAW_DIR / "documents.xlsx",     header=1)

In [15]:
companies_clean = companies_df.copy()

companies_clean.columns = (
    companies_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

dim_company = companies_clean[[
    "id",
    "company_name",
    "about_company",
    "website",
    "nse_profile",
    "bse_profile",
    "face_value",
    "book_value",
    "roce_percentage",
    "roe_percentage",
]].copy()

dim_company = dim_company.rename(columns={"id": "company_id"})
dim_company["company_id"] = dim_company["company_id"].astype(str).str.strip()

dim_company.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   company_id       92 non-null     object
 1   company_name     92 non-null     object
 2   about_company    92 non-null     object
 3   website          91 non-null     object
 4   nse_profile      91 non-null     object
 5   bse_profile      91 non-null     object
 6   face_value       91 non-null     float64
 7   book_value       91 non-null     float64
 8   roce_percentage  91 non-null     float64
 9   roe_percentage   90 non-null     float64
dtypes: float64(4), object(6)
memory usage: 7.3+ KB

In [17]:
balancesheet_clean = balancesheet_df.copy()

balancesheet_clean.columns = (
    balancesheet_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

balancesheet_clean["company_id"] = balancesheet_clean["company_id"].astype(str).str.strip()
balancesheet_clean["year"] = balancesheet_clean["year"].astype(str).str.strip()

balancesheet_clean["fiscal_year"] = (
    balancesheet_clean["year"]
    .str.extract(r"(\d{4})", expand=False)
    .astype(int)
)

fact_balance_sheet = balancesheet_clean[[
    "company_id",
    "fiscal_year",
    "equity_capital",
    "reserves",
    "borrowings",
    "other_liabilities",
    "total_liabilities",
    "fixed_assets",
    "cwip",
    "investments",
    "other_asset",
    "total_assets",
]].copy()

fact_balance_sheet["debt_to_equity"] = (
    fact_balance_sheet["borrowings"] / fact_balance_sheet["equity_capital"]
)

fact_balance_sheet["equity_ratio"] = (
    (fact_balance_sheet["equity_capital"] + fact_balance_sheet["reserves"])
    / fact_balance_sheet["total_assets"]
)

fact_balance_sheet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1312 entries, 0 to 1311
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   company_id         1312 non-null   object
 1   fiscal_year        1312 non-null   int64
 2   equity_capital     1312 non-null   float64
 3   reserves           1312 non-null   int64
 4   borrowings         1312 non-null   int64
 5   other_liabilities  1312 non-null   int64
 6   total_liabilities  1312 non-null   int64
 7   fixed_assets       1312 non-null   int64
 8   cwip               1312 non-null   int64
 9   investments        1312 non-null   int64
 10  other_asset        1312 non-null   int64
 11  total_assets       1312 non-null   int64
 12  debt_to_equity     1312 non-null   float64
 13  equity_ratio       1312 non-null   float64
dtypes: float64(3), int64(10), object(1)
memory usage: 143.6+ KB

In [18]:
profitandloss_clean = profitandloss_df.copy()

profitandloss_clean.columns = (
    profitandloss_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

profitandloss_clean["company_id"] = profitandloss_clean["company_id"].astype(str).str.strip()
profitandloss_clean["year"] = profitandloss_clean["year"].astype(str).str.strip()

profitandloss_clean["fiscal_year"] = (
    profitandloss_clean["year"]
    .str.extract(r"(\d{4})", expand=False)
)
profitandloss_clean["fiscal_year"] = profitandloss_clean["fiscal_year"].astype("float")

fact_profit_loss = profitandloss_clean[[
    "company_id",
    "fiscal_year",
    "sales",
    "expenses",
    "operating_profit",
    "opm_percentage",
    "other_income",
    "interest",
    "depreciation",
    "profit_before_tax",
    "tax_percentage",
    "net_profit",
    "eps",
    "dividend_payout",
]].copy()

fact_profit_loss["net_margin"] = (
    fact_profit_loss["net_profit"] / fact_profit_loss["sales"]
)

fact_profit_loss["operating_margin"] = (
    fact_profit_loss["operating_profit"] / fact_profit_loss["sales"]
)

fact_profit_loss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1276 entries, 0 to 1275
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   company_id         1276 non-null   object
 1   fiscal_year        1176 non-null   float64
 2   sales              1276 non-null   int64
 3   expenses           1276 non-null   int64
 4   operating_profit   1263 non-null   float64
 5   opm_percentage     1261 non-null   float64
 6   other_income       1276 non-null   int64
 7   interest           1276 non-null   int64
 8   depreciation       1276 non-null   int64
 9   profit_before_tax  1276 non-null   int64
 10  tax_percentage     1181 non-null   float64
 11  net_profit         1276 non-null   int64
 12  eps                1271 non-null   float64
 13  dividend_payout    1173 non-null   float64
 14  net_margin         1275 non-null   float64
 15  operating_margin   1262 non-null   float64
dtypes: float64(8), int64(7), object(1)
memory usage: 159.6+ KB

In [19]:
cashflow_clean = cashflow_df.copy()

cashflow_clean.columns = (
    cashflow_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

cashflow_clean["company_id"] = cashflow_clean["company_id"].astype(str).str.strip()
cashflow_clean["year"] = cashflow_clean["year"].astype(str).str.strip()

cashflow_clean["fiscal_year"] = (
    cashflow_clean["year"]
    .str.extract(r"(\d{4})", expand=False)
)
cashflow_clean["fiscal_year"] = cashflow_clean["fiscal_year"].astype("float")

fact_cash_flow = cashflow_clean[[
    "company_id",
    "fiscal_year",
    "operating_activity",
    "investing_activity",
    "financing_activity",
    "net_cash_flow",
]].copy()

fact_cash_flow["free_cash_flow"] = (
    fact_cash_flow["operating_activity"] - fact_cash_flow["investing_activity"]
)

fact_cash_flow.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1187 entries, 0 to 1186
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   company_id          1187 non-null   object
 1   fiscal_year         1175 non-null   float64
 2   operating_activity  1185 non-null   float64
 3   investing_activity  1185 non-null   float64
 4   financing_activity  1185 non-null   float64
 5   net_cash_flow       1185 non-null   float64
 6   free_cash_flow      1185 non-null   float64
dtypes: float64(6), object(1)
memory usage: 65.0+ KB

In [20]:
# Analysis
analysis_clean = analysis_df.copy()
analysis_clean.columns = (
    analysis_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)
analysis_clean["company_id"] = analysis_clean["company_id"].astype(str).str.strip()
fact_analysis = analysis_clean.copy()

# Pros & Cons
prosandcons_clean = prosandcons_df.copy()
prosandcons_clean.columns = (
    prosandcons_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)
prosandcons_clean["company_id"] = prosandcons_clean["company_id"].astype(str).str.strip()
fact_pros_cons = prosandcons_clean.copy()

# Documents
documents_clean = documents_df.copy()
documents_clean.columns = (
    documents_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)
documents_clean["company_id"] = documents_clean["company_id"].astype(str).str.strip()

In [21]:
from pathlib import Path

CLEAN_DIR = Path("data/clean")
CLEAN_DIR.mkdir(parents=True, exist_ok=True)

dim_company.to_csv(CLEAN_DIR / "dim_company.csv", index=False)
fact_balance_sheet.to_csv(CLEAN_DIR / "fact_balance_sheet.csv", index=False)
fact_profit_loss.to_csv(CLEAN_DIR / "fact_profit_loss.csv", index=False)
fact_cash_flow.to_csv(CLEAN_DIR / "fact_cash_flow.csv", index=False)
fact_analysis.to_csv(CLEAN_DIR / "fact_analysis.csv", index=False)
fact_pros_cons.to_csv(CLEAN_DIR / "fact_pros_cons.csv", index=False)
documents_clean.to_csv(CLEAN_DIR / "documents.csv", index=False)